### ISSUE TITLE
Trouble connecting SQL DB

### ISSUE THREAD

**Issue by dewens12** [Bajdzis/vscode-database#139]
at Immediate.messageQueue.size.setImmediate (c:\Users\ewens\.vscode\extensions\mtxr.sqltools-0.21.1\extension.js:1:23936)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)
	at process.topLevelDomainCallback (domain.js:121:23)] code: -32001, data: { dialect: 'MSSQL', dialectOptions: {} } }
ERROR: Error:  { [Error: Failed to connect to N1419-EWENS3-PC:1433 - Could not connect (sequence)
	at c:\Users\ewens\.vscode\extensions\mtxr.sqltools-0.21.1\extension.js:1:22985
	at c:\Users\ewens\.vscode\extensions\mtxr.sqltools-0.21.1\extension.js:1:23392
	at Immediate.messageQueue.size.setImmediate (c:\Users\ewens\.vscode\extensions\mtxr.sqltools-0.21.1\extension.js:1:23936)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)
	at process.topLevelDomainCallback (domain.js:121:23)] code: -32001, data: { dialect: 'MSSQL', dialectOptions: {} } }
INFO: Executing SQLTools.showOutputChannel
INFO: Executing SQLTools.showOutputChannel

**Comment by Bajdzis** [comment]
Stack trace show other extension `mtxr.sqltools` please create other issue in correct project ;-)
