### ISSUE TITLE
Get exception when querying describe [table_name]

### ISSUE THREAD

**Issue by vuongggggg** [Bajdzis/vscode-database#31]
This extension is awesome. I very like it. Thanks for the authors.

But I have some little issues:
1.  When I try to get description of table by the query
`DESCRIBE table_name`.
The console log error here:
```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:10 MySQL Error: Error: Cannot enqueue Query after fatal error.
	at Protocol._validateEnqueue (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\node_modules\mysql\lib\protocol\Protocol.js:199:16)
	at Protocol._enqueue (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\node_modules\mysql\lib\protocol\Protocol.js:135:13)
	at Connection.query (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\node_modules\mysql\lib\Connection.js:208:25)
	at Promise (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension\engine\mysql.js:71:29)
	at Promise (<anonymous>)
	at MySQLType.queryPromise (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension\engine\mysql.js:70:16)
	at sqlMulti.split.forEach.sql (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension\engine\AbstractServer.js:57:35)
	at Array.forEach (native)
	at MySQLType.queryPromiseMulti (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension\engine\AbstractServer.js:51:29)
	at Menager.queryPromiseMulti (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension\Menager.js:91:39)
	at execQuery (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension.js:67:13)
	at getBuildQueryDocument.then (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension.js:58:9)
	at <anonymous>
```

2. I couldn't change the database after the first error occurred.

Log here:

```
shell.ts:459 MySQL Error: Error: Cannot enqueue Query after fatal error.
	at Protocol._validateEnqueue (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\node_modules\mysql\lib\protocol\Protocol.js:199:16)
	at Protocol._enqueue (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\node_modules\mysql\lib\protocol\Protocol.js:135:13)
	at Connection.query (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\node_modules\mysql\lib\Connection.js:208:25)
	at Promise (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension\engine\mysql.js:71:29)
	at Promise (<anonymous>)
	at MySQLType.queryPromise (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension\engine\mysql.js:70:16)
	at Promise (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension\engine\mysql.js:86:18)
	at Promise (<anonymous>)
	at MySQLType.getDatabase (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension\engine\mysql.js:85:16)
	at Menager.getDatabase (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension\Menager.js:96:35)
	at changeDB (C:\Users\vuongbq\.vscode\extensions\bajdzis.vscode-database-1.2.0\extension.js:214:17)
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:412039)
	at t.e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:509277)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354645)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354335)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:353362
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:355281
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:85085
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84368)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86090)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:144000)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

Hope to get the answer. Thanks!

**Comment by Bajdzis** [comment]
On my computer DESCRIBE is working. I need more details. Please describe you problem in steps.

**Comment by vuongggggg** [comment]
Sorry, I didn't pay attention on this issue for a long time, now I would like to close it without confirmation (because I can't). Thanks for your anwser Bajdzis.
