### ISSUE TITLE
Postgresql connection SSL enabled

### ISSUE THREAD

**Issue by hcabnettek** [Bajdzis/vscode-database#54]
How do I indicate ssl mode is required? I provide URL and port, user, pass, database, but there is no option to say ssl enabled. How do I do that?

**Comment by joschne** [comment]
Any news on this? Would be very helpful.

**Comment by paulana** [comment]
Any news on this?

**Comment by Bajdzis** [comment]
I'm starting work on it ;)

**Comment by Bajdzis** [comment]
I think the feature is worked in 2.0.1 version. Could you check if everything works?

@paulana @joschne @hcabnettek

**Comment by brooksgarrett** [comment]
Confirmed not working in 2.0.1 or 2.0.3. 

The intent of this issue is to connect to a PSQL database via username and password when the remote database has SSL enabled. The problem is the tail end of line one, `SSL off`

```
Connection error! PostgreSQL Error: error: no pg_hba.conf entry for host "REDACTED_IP_ADDRESS", user "REDACTED_DATABASE_NAME", database "REDACTED_DATABASE_NAME", SSL off
at Connection.parseE (/Users/brooks/.vscode/extensions/bajdzis.vscode-database-2.0.1/node_modules/pg/lib/connection.js:567:11)
at Connection.parseMessage (/Users/brooks/.vscode/extensions/bajdzis.vscode-database-2.0.1/node_modules/pg/lib/connection.js:391:17)
at Socket.<anonymous> (/Users/brooks/.vscode/extensions/bajdzis.vscode-database-2.0.1/node_modules/pg/lib/connection.js:129:22)
at Socket.emit (events.js:182:13)
at addChunk (_stream_readable.js:279:12)
at readableAddChunk (_stream_readable.js:264:11)
at Socket.Readable.push (_stream_readable.js:219:10)
at TCP.onread (net.js:636:20)
```
